on: workflow_dispatch
jobs:
  create_package:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v4.0.1
    - name: Clone Repo
      run: |
        git clone https://github.com/skypaint-96/ADHelpers.git -v
    - name: Build
      run: |
        dotnet build '.\ADHelpers\ADHelpers.csproj' -c release -v d
    - name: Create Manifest
      run: |
        import-module '.\adhelpers\bin\release\netstandard2.0\adhelpers.dll' -scope local;
        $version = (get-module AdHelpers).version;
        remove-module adhelpers -force;
        New-ModuleManifest -Path '.\adhelpers\bin\release\netstandard2.0\AdHelpers.psd1' `
            -RootModule 'ADHelpers' `
            -moduleversion $version `
            -Guid '55b99733-8488-493e-a3cd-05cfcea90974' `
            -Author 'Mason Kerr' `
            -CompanyName 'Pasifico' `
            -Copyright '(c) 2024 Mason Kerr. All rights reserved.' `
            -CmdletsToExport '*' `
            -VariablesToExport '*' `
            -LicenseUri 'https://github.com/skypaint-96/ADHelpers/blob/master/LICENSE.txt' `
            -ProjectUri 'https://github.com/skypaint-96/ADHelpers' `
            -DefaultCommandPrefix 'ADEX'
    - name: Zip
      run: |
        compress-archive -path .\adhelpers\bin\release\netstandard2.0\ -destinationpath .\adhelpers.zip -Verbose
    
