on: workflow_dispatch
jobs:
  create_package:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v4.0.1
    - name: Clone Repo, Build, Create Manifest, Zip
      run: |
        git clone https://github.com/skypaint-96/ADHelpers.git -v
        dotnet build '.\ADHelpers\ADHelpers.csproj' -c release -v d
        start-process -FilePath pwsh -ArgumentList '-f ".\adhelpers\bin\debug\netstandard2.0\createmanifest.ps1" -wd ".\adhelpers\bin\debug\netstandard2.0\"' -Verbose
        compress-archive -path .\adhelpers\bin\release\netstandard2.0\ -destinationpath .\adhelpers.zip -Verbose
    
