on: workflow_dispatch
jobs:
  create_package:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v4.0.1
    - name: Clone Repo
      run: |
        git clone https://github.com/skypaint-96/ADHelpers.git;
    - name: Build
      run: |
        dotnet .\adhelpers\adhelpers.csproj build -c release
    - name: Create Manifest
      run: |
        start-process -FilePath pwsh -ArgumentList '-f ".\adhelpers\bin\debug\netstandard2.0\createmanifest.ps1" -wd ".\adhelpers\bin\debug\netstandard2.0\"' 
    - name: Zip
      run: |
        compress-archive -path .\adhelpers\ -destinationpath .\adhelpers.zip
    
