on: workflow_dispatch
jobs:
  create_package:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v4.0.1
    - name: build release
      run: |
        write-host (pwd);
        git clone https://github.com/skypaint-96/ADHelpers.git;
        cd adhelpers;
        dotnet build -c release
    
