on: workflow_dispatch
jobs:
  create_package:
    runs-on: windows-latest
    steps:
    - name: Setup .NET Core SDK 
      uses: actions/setup-dotnet@v4.0.1
    - name: build release
      run: |
        dotnet build -c release
    
